version: '2'

volumes:
  orderer.certification-network.com:
  peer0.iit.certification-network.com:
  peer1.iit.certification-network.com:
  peer0.mhrd.certification-network.com:
  peer1.mhrd.certification-network.com:
  peer0.upgrad.certification-network.com:
  peer1.upgrad.certification-network.com:

networks:
  certification:

services:

  ca.iit.certification-network.com:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.iit.certification-network.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.iit.certification-network.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/296d37c753e59e91174fe06df8dad4e9334703135e8a5945dfd3aa4e57389c88_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.iit.certification-network.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/296d37c753e59e91174fe06df8dad4e9334703135e8a5945dfd3aa4e57389c88_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/iit.certification-network.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.iit.certification-network.com
    networks:
      - certification

  ca.mhrd.certification-network.com:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.mhrd.certification-network.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.mhrd.certification-network.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/7f5ae3fccfa515b17b0402f2dce4b1a8dc2e0151aae545e1d89d0a23a4162443_sk
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.mhrd.certification-network.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/7f5ae3fccfa515b17b0402f2dce4b1a8dc2e0151aae545e1d89d0a23a4162443_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/mhrd.certification-network.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.mhrd.certification-network.com
    networks:
      - certification

  ca.upgrad.certification-network.com:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.upgrad.certification-network.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.upgrad.certification-network.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/fa1860dc4682fd825681760954e2f0ab59b1cd63695df5a649e6c084accb5d62_sk
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.upgrad.certification-network.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/fa1860dc4682fd825681760954e2f0ab59b1cd63695df5a649e6c084accb5d62_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/upgrad.certification-network.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.upgrad.certification-network.com
    networks:
      - certification

  orderer.certification-network.com:
    extends:
      file:   docker-base/docker-compose-base.yaml
      service: orderer.certification-network.com
    container_name: orderer.certification-network.com
    networks:
      - certification

  peer0.iit.certification-network.com:
    container_name: peer0.iit.certification-network.com
    extends:
      file:  docker-base/docker-compose-base.yaml
      service: peer0.iit.certification-network.com
    networks:
      - certification

  peer1.iit.certification-network.com:
    container_name: peer1.iit.certification-network.com
    extends:
      file:  docker-base/docker-compose-base.yaml
      service: peer1.iit.certification-network.com
    networks:
      - certification

  peer0.mhrd.certification-network.com:
    container_name: peer0.mhrd.certification-network.com
    extends:
      file:  docker-base/docker-compose-base.yaml
      service: peer0.mhrd.certification-network.com
    networks:
      - certification

  peer1.mhrd.certification-network.com:
    container_name: peer1.mhrd.certification-network.com
    extends:
      file:  docker-base/docker-compose-base.yaml
      service: peer1.mhrd.certification-network.com
    networks:
      - certification

  peer0.upgrad.certification-network.com:
    container_name: peer0.upgrad.certification-network.com
    extends:
      file:  docker-base/docker-compose-base.yaml
      service: peer0.upgrad.certification-network.com
    networks:
      - certification

  peer1.upgrad.certification-network.com:
    container_name: peer1.upgrad.certification-network.com
    extends:
      file:  docker-base/docker-compose-base.yaml
      service: peer1.upgrad.certification-network.com
    networks:
      - certification

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.iit.certification-network.com:7051
      - CORE_PEER_LOCALMSPID=AmazonMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/iit.certification-network.com/peers/peer0.iit.certification-network.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/iit.certification-network.com/peers/peer0.iit.certification-network.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/iit.certification-network.com/peers/peer0.iit.certification-network.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/iit.certification-network.com/users/Admin@iit.certification-network.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./../chaincode/:/opt/gopath/src/github.com/hyperledger/fabric/peer/chaincode/
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - ca.iit.certification-network.com
      - ca.mhrd.certification-network.com
      - ca.upgrad.certification-network.com
      - orderer.certification-network.com
      - peer0.iit.certification-network.com
      - peer1.iit.certification-network.com
      - peer0.mhrd.certification-network.com
      - peer1.mhrd.certification-network.com
      - peer0.upgrad.certification-network.com
      - peer1.upgrad.certification-network.com
    networks:
      - certification

#  chaincode:
#    container_name: chaincode
#    image: hyperledger/fabric-ccenv:latest
#    tty: true
#    environment:
#      - GOPATH=/opt/gopath
#      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
#      - FABRIC_LOGGING_SPEC=INFO
#      - CORE_PEER_ID=chaincode
#      - CORE_PEER_ADDRESS=peer0.iit.certification-network.com:7051
#      - CORE_PEER_LOCALMSPID=iitMSP
#      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/iit.certification-network.com/users/Admin@iit.certification-network.com/msp
#      - CORE_PEER_TLS_ENABLED=true
#      - CORE_TLS_CLIENT_KEY_PATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/iit.certification-network.com/users/Admin@iit.certification-network.com/tls/client.key
#      - CORE_TLS_CLIENT_CERT_PATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/iit.certification-network.com/users/Admin@iit.certification-network.com/tls/client.crt
#      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/iit.certification-network.com/users/Admin@iit.certification-network.com/tls/ca.crt
#    working_dir: /opt/gopath/src/chaincode
#    command: /bin/bash -c 'sleep 6000000'
#    volumes:
#      - /var/run/:/host/var/run/
#      - ./../chaincode:/opt/gopath/src/chaincode
#    networks:
#      - certification

